name: StreamingThings
version: 1.0
main: StreamingThings
api-version: 1.21
author: hicupalot

commands:
  Timer:
    description: Starts a timer
    aliases: [starttimer, timerstart]
  coinflip:
    description: Flips a coin
    aliases: [headsortails, flipcoin]
  StopTimer:
    description: Stops the running timer
    aliases: [timerstop, stopcurrenttimer, canceltimer, timercancel]
  PlayerRaffle:
    description: Chooses a player at random
    aliases: [ raffle, randomplayer ]
  randomtp:
    description: Teleports you to a random player
    aliases: [tprandom, rtp]
  permissions:
    streamingthings.staff:
      descritpion: 'Allows Access To Staff Commands'
      default: op
    streamingthings.admin:
      descritpion: 'Allows access to Admin Commands'
      default: op
